apiVersion: v1
kind:Pod
metadata:
	name: hello-world
spec:
       replicas: 1
       template:
           metadata:
                        labels:
	               app: hello-world
	               spec:
                                        containers:
                                                - name: hello-world
	                                image: Niranjan/node-web-app:v1
	                                ports:
			- containerPort: 8000